/*
Test generated by RoostGPT for test products-integration-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Delete an existing product\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a DELETE request to "/api/products/1"\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the product with ID 1 should no longer exist',
  title: 'Delete an existing product'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.junit.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class deleteAnExistingProductTest {
    
    // Test for deleting an existing product
    @Test
    public void deleteProductTest() {
        
        // Set base URL from environment variable
        String roostServerUrl = System.getenv("ROOST_SERVER_URL");
        RestAssured.baseURI = roostServerUrl;
        
        // Given a product exists with ID 1 
        given()
            .pathParam("productId", 1)
        .when()
            .get("/api/products/{productId}")
        .then()
            .assertThat()
            .statusCode(200)
            .body("id", equalTo(1));
        
        // When a DELETE request is sent
        Response response = given()
            .pathParam("productId", 1)
        .when()
            .delete("/api/products/{productId}")
        .then()
            .assertThat()
            .statusCode(200)
            .extract()
            .response();
        
        // The product with ID 1 should no longer exist
        given()
            .pathParam("productId", 1)
        .when()
            .get("/api/products/{productId}")
        .then()
            .assertThat()
            .statusCode(404);
            
        // Assert the response message
        String responseMessage = response.asString();
        assert(responseMessage.equals("Product deleted"));
    }
}
