/*
Test generated by RoostGPT for test products-integration-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
// Necessary imports
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import org.junit.jupiter.api.Test;
import io.restassured.http.ContentType;

// Package Declaration
package com.bootexample4.RoostTest;

public class getAllProductsTest {

    // Scenario: Get all products
    @Test
    public void testGetAllProducts() {
        // Set up request
        String serverUrl = System.getenv("ROOST_SERVER_URL");
        String endpoint = "/api/products";
        String url = serverUrl + endpoint;

        // Request
        given()
            .baseUri(url)
            .contentType(ContentType.JSON)
        .when()
            .get()
        .then()
            // Assert that the list of products returned should be empty
            .assertThat()
            .statusCode(200)
            .body("", is(emptyArray()))
            .and()
            // Furthermore, make sure all expected fields are present
            .body(matchesJsonSchemaInClasspath("products.json"));
    }
}
