/*
Test generated by RoostGPT for test products-integration-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
package com.bootexample4.RoostTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.empty;
import org.junit.Test;

public class getAllProductsTest {

  // Define base URL
  private static String ROOST_SERVER_URL = System.getenv("ROOST_SERVER_URL");

  @Test
  // Scenario: Get all products
  public void getAllProducts() {

    // When the client sends a GET request "/api/products" to get the list of all products
    
    given().when().get(ROOST_SERVER_URL + "/api/products")
      // Then the list of products returned should be empty
      .then().body("", empty());
  }
}
