/*
Test generated by RoostGPT for test products-integration-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

import io.restassured.builder.RequestSpecBuilder;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.junit.BeforeClass;
import org.junit.Test;

public class getAProductByIdTest {

    private static RequestSpecification spec;

    @BeforeClass
    public static void setUp() {
        spec = new RequestSpecBuilder()
                .setBaseUri(System.getenv("ROOST_SERVER_URL"))
                .setBasePath("/api/products")
                .build();
    }

    @Test
    public void testGetProductById() {
        // Given there is an existing product with ID 1
        int productId = 1;

        // When the client sends a GET request "/api/products/1" to get a product by its id
        Response response = given()
                .spec(spec)
                .pathParam("productId", productId)
                .when()
                .get("/{productId}");

        // Then the response status code should be 200. 
        // And the response should contain the product with ID 1
        response.then()
                .statusCode(200)
                .body("id", equalTo(productId))
                .body("name", is(notNullValue()))
                .body("description", is(notNullValue()))
                .body("price", is(notNullValue()));

        // Description : This test will pass if there is a product with ID 1 and 
        // the product details are shown correctly in the response.
    }
}
