/*
Test generated by RoostGPT for test products-integration-rest-assured using AI Type Azure Open AI and AI Model roost-gpt4-32k

{
  background: null,
  rule: null,
  scenario: 'Get a product by ID\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a GET request "/api/products/1" to get a product by its id\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the response should contain the product with ID 1',
  title: 'Get a product by ID'
}

*/
package com.bootexample4.RoostTest;

import static io.restassured.RestAssured.*;

import io.restassured.response.Response;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.is;

public class getAProductByIdTest {

    @Test
    public void getProductByIdTest() {
        // The client sends a GET request "/api/products/1" to get a product by its id
        Response response = given()
                .baseUri(System.getenv("ROOST_SERVER_URL"))
                .basePath("/api/products/{id}")
                .pathParam("id", 1)
                .when()
                .get();

        // Then the response status code should be 200
        response.then().statusCode(200);

        // And the response should contain the product with ID 1
        response.then().assertThat()
                .body("id", is(1));

        // Check all properties in API spec to ensure correct response
        response.then().assertThat()
                .body("name", is("string"))
                .body("description", is("string"))
                .body("price", is("integer"));
    }
}
