// ********RoostGPT********
/*
Test generated by RoostGPT for test product-rest-assured using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /products_post for http method type POST in rest-assured framework

RoostTestHash=dcd186097b


*/

// ********RoostGPT********
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.json.JSONObject;
import org.json.XML;
import org.json.JSONException;
import org.json.JSONArray;
import java.util.Arrays;

public class productsPostTest {

	List<Map<String, String>> envList = new ArrayList<>();

	@BeforeEach
	public void setUp() {
		TestdataLoader dataloader = new TestdataLoader();
		String[] envVarsList = { "" };
		envList = dataloader.load("src/test/java/com/bootexample4/RoostTest/productsPostTest.csv", envVarsList);
	}

	@Test
	public void productsPost_Test() throws JSONException {
		this.setUp();
		Integer testNumber = 1;
		for (Map<String, String> testData : envList) {
			RestAssured.baseURI = (testData.get("BASE_URL") != null && !testData.get("BASE_URL").isEmpty())
					? testData.get("BASE_URL") : "http://52.66.106.18:8080/api";

			Response responseObj = given().contentType(ContentType.JSON)
				.body("{\n" + "  \"id\": \"" + (testData.get("id") != null ? testData.get("id") : "") + "\",\n"
						+ "  \"name\": \"" + (testData.get("name") != null ? testData.get("name") : "") + "\",\n"
						+ "  \"description\": \""
						+ (testData.get("description") != null ? testData.get("description") : "") + "\",\n"
						+ "  \"price\": \"" + (testData.get("price") != null ? testData.get("price") : "") + "\n" + "}")
				.when()
				.post("/products")
				.then()
				.extract()
				.response();
			JsonPath response;
			String contentType = responseObj.getContentType();

			System.out.printf("Test Case %d: productsPost_Test \n", testNumber++);
			System.out.println("Request: POST /products");
			System.out.println("Status Code: " + responseObj.statusCode());
			if (testData.get("statusCode") != null) {
				String statusCodeFromCSV = testData.get("statusCode");
				if (statusCodeFromCSV.contains("X")) {
					MatcherAssert.assertThat(
							"Expected a status code of category " + statusCodeFromCSV + ", but got "
									+ Integer.toString(responseObj.statusCode()) + " instead",
							Integer.toString(responseObj.statusCode()).charAt(0), equalTo(statusCodeFromCSV.charAt(0)));
				}
				else {
					MatcherAssert.assertThat(Integer.toString(responseObj.statusCode()), equalTo(statusCodeFromCSV));
				}
			}
			else {
				List<Integer> expectedStatusCodes = Arrays.asList(200, 405);
				MatcherAssert.assertThat(responseObj.statusCode(), is(in(expectedStatusCodes)));
			}
			String stringifiedStatusCode = Integer.toString(responseObj.statusCode());
			switch (responseObj.statusCode()) {

				case 200:
					stringifiedStatusCode = "200";
					MatcherAssert.assertThat(contentType, equalTo("application/json"));
					break;

			}

			switch (Integer.toString(responseObj.statusCode()).charAt(0)) {

			}

			if (contentType.contains("application/xml") || contentType.contains("text/xml")) {
				String xmlResponse = responseObj.asString();
				JSONObject jsonResponse = XML.toJSONObject(xmlResponse);
				JSONObject jsonData = jsonResponse.getJSONObject("xml");
				String jsonString = jsonData.toString();
				response = new JsonPath(jsonString);

			}
			else if (contentType.contains("application/json")) {
				response = responseObj.jsonPath();
			}
			else {
				System.out.println("Response content type found: " + contentType
						+ ", but RoostGPT currently only supports the following response content types: application/json,text/xml,application/xml");
				continue;
			}

			if (stringifiedStatusCode.equals("200")) {
				System.out.println("Description: Successful operation");

				if (response.get("id") != null) {
					MatcherAssert.assertThat(response.get("id"), instanceOf(Integer.class));
				}

				if (response.get("name") != null) {
					MatcherAssert.assertThat(response.get("name"), instanceOf(String.class));
				}

				if (response.get("description") != null) {
					MatcherAssert.assertThat(response.get("description"), instanceOf(String.class));
				}

				if (response.get("price") != null) {
					MatcherAssert.assertThat(response.get("price"), instanceOf(Integer.class));
				}
			}
			if (stringifiedStatusCode.equals("405")) {
				System.out.println("Description: Invalid input");
			}

		}
	}

}
