# ********RoostGPT********

# Test generated by RoostGPT for test API_Karate_DB_DBRX using AI Type  and AI Model 
# 
# Feature file generated for /products_post for http method type POST 
# RoostTestHash=dcd186097b
# 
# 

# ********RoostGPT********

def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
url urlBase
def authToken = karate.properties['AUTH_TOKEN']
headers authorization = 'Bearer ' + authToken
