# ********RoostGPT********

# Test generated by RoostGPT for test roost-io-my-products-api using AI Type  and AI Model 
# 
# Feature file generated for /products_get for http method type GET 
# RoostTestHash=70199667a6
# 
# 

# ********RoostGPT********
Feature: Get All Products

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN'] ? karate.properties['AUTH_TOKEN'] : 'default_token'
    * configure headers = { Authorization: '#(authToken)' }

  Scenario: Verify successful retrieval of all products
    Given path '/products'
    When method get
    Then status 200
    And match $ == '#array'
    And match each $ contains { 'id': '#number', 'name': '#string', 'description': '#string', 'price': '#number' }
