# ********RoostGPT********

# Test generated by RoostGPT for test API_Karate_DB_DBRX using AI Type DBRX and AI Model undefined
# 
# Feature file generated for /products/{productId}_delete for http method type DELETE 
# RoostTestHash=befb82c928
# 
# 

# ********RoostGPT********
Feature: Product management API test

  Background:
    Given a valid productId provided

  Scenario: Check response with valid productId
    When a DELETE request is made to /products/<validProductId>
    Then the response code should be 200
    And the response body should contain the following properties:
      | property  | type    | pattern         |
      | productId | integer | ^[-+]?[0-9]*$   |
      | status    | string  | ^[A-Za-z0-9_]+$ |

  Scenario: Check response with invalid productId
    Given an invalid productId provided
    When a DELETE request is made to /products/<invalidProductId>
    Then the response code should be 404
    And the response body should be null

  Scenario: Check response with missing productId
    Given a missing productId provided
    When a DELETE request is made to /products/<missingProductId>
    Then the response code should be 400
    And the response body should be of type JSON with name "error"

    Examples:
      | read('products_productId_delete.csv') |
