# ********RoostGPT********

# Test generated by RoostGPT for test roost-io-my-products-api using AI Type  and AI Model 
# 
# Feature file generated for /products/{productId}_put for http method type PUT 
# RoostTestHash=7b2a6b6959
# 
# 

# ********RoostGPT********
Feature: Update Product API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Test Update Product API with valid inputs
    Given path 'products', '<productId>'
    And request { id: '#<id>', name: '<name>', description: '<description>', price: '#<price>' }
    When method put
    Then status 200
    And match response.id == '#integer'
    And match response.name == '#string'
    And match response.description == '#string'
    And match response.price == '#integer'

    Examples:
      | read('products_productId_put.csv') |

  Scenario: Test Update Product API with non-existent product
    Given path 'products', '999999'
    And request { id: '999999', name: 'fake product', description: 'fake description', price: '999' }
    When method put
    Then status 404
