# ********RoostGPT********

# Test generated by RoostGPT for test API_Karate_DB_DBRX using AI Type DBRX and AI Model undefined
# 
# Feature file generated for /products_get for http method type GET 
# RoostTestHash=70199667a6
# 
# 

# ********RoostGPT********
Feature: ROOST API for getting products

  Background:
    * url 'https://roost-api.herokuapp.com'

  Scenario: Get all products with valid authorization token
    Given path '/products'
    And header Authorization = 'Bearer Kasparovka'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products with authorization header
    Given path '/products'
    And header Authorization = 'Bearer Kasparovka'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products with authorization header and Emily
    Given path '/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products with authorization header, Emily, Steve
    Given path '/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    And header Steve = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products with authorization header, Emily, Steve, and Robby
    Given path '/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    And header Steve = 'true'
    And header Robby = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products using API token and authorization header
    Given url 'https://roost-api.herokuapp.com/products'
    And header Authorization = 'Bearer Kasparovka'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products using API token, authorization header, and Emily
    Given url 'https://roost-api.herokuapp.com/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products using API token, authorization header, Emily, and Steve
    Given url 'https://roost-api.herokuapp.com/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    And header Steve = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }

  Scenario: Get all products using API token, authorization header, Emily, Steve, and Robby
    Given url 'https://roost-api.herokuapp.com/products'
    And header Authorization = 'Bearer Kasparovka'
    And header Emily = 'true'
    And header Steve = 'true'
    And header Robby = 'true'
    When method get
    Then status 200
    And match response contains { type: 'array' }
